// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgatuaofskiomzwoipei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnYXR1YW9mc2tpb216d29pcGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjgyNjIsImV4cCI6MjA2NjAwNDI2Mn0.OoqWovEwEaVOWY9POWS2bc7wPF_-lLCi9rqwRrZyBK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);